[package]
name        = "cuprate-regtest"
version     = "0.0.0"
edition     = "2021"
description = "regtest node for integration testing"

[lints]
workspace = true

[dependencies]
cuprate-blockchain      = { path = "../storage/blockchain" }
cuprate-database        = { path = "../storage/database" }
cuprate-consensus-rules = { path = "../consensus/rules" }
cuprate-types           = { path = "../types/types" }
monero-oxide            = { workspace = true }
monero-wallet           = { workspace = true }
curve25519-dalek        = { workspace = true, features = ["alloc"] }
rand                    = { workspace = true, features = ["std", "getrandom"] }
tempfile                = { workspace = true }
thiserror               = { workspace = true }

[dev-dependencies]
tokio   = { workspace = true, features = ["rt", "macros"] }
zeroize = { workspace = true, features = ["alloc"] }
